/* =========================================================
   ASSUMED TABLES
   ---------------------------------------------------------
   sales            (user_id INT, created_date DATE, product_id INT)
   product          (product_id INT, product_name VARCHAR(100), price INT)
   users            (user_id INT, signup_date DATE)
   user_name        (user_id INT, user_name VARCHAR(100))
   goldusers_signup (user_id INT, gold_signup_date DATE)
   ========================================================= */

/* Q1. Total sales revenue generated by each product */
SELECT
    p.product_id,
    p.product_name,
    SUM(p.price) AS total_revenue
FROM sales AS s
JOIN product AS p
    ON s.product_id = p.product_id
GROUP BY
    p.product_id,
    p.product_name
ORDER BY
    total_revenue DESC;
GO


/* Q2. Top 3 products by sales revenue */
SELECT TOP (3)
    p.product_id,
    p.product_name,
    SUM(p.price) AS total_revenue
FROM sales AS s
JOIN product AS p
    ON s.product_id = p.product_id
GROUP BY
    p.product_id,
    p.product_name
ORDER BY
    total_revenue DESC;
GO


/* Q3. How many users have signed up and how many took gold membership */
SELECT
    (SELECT COUNT(*) FROM users)                        AS total_signed_up_users,
    (SELECT COUNT(DISTINCT user_id) FROM goldusers_signup) AS total_gold_members;
GO


/* Q4. Revenue generated from orders placed WHILE user is a gold member */
SELECT
    SUM(p.price) AS gold_period_revenue
FROM goldusers_signup AS g
JOIN sales AS s
    ON s.user_id = g.user_id
   AND s.created_date >= g.gold_signup_date      -- only after becoming gold
JOIN product AS p
    ON s.product_id = p.product_id;
GO


/* Q5. Revenue comparison: gold-member orders vs non-gold orders */
WITH sales_with_flag AS (
    SELECT
        s.user_id,
        s.created_date,
        s.product_id,
        p.price,
        CASE
            WHEN g.gold_signup_date IS NOT NULL
                 AND s.created_date >= g.gold_signup_date
                THEN 'Gold_Order'
            ELSE 'Non_Gold_Order'
        END AS order_type
    FROM sales AS s
    JOIN product AS p
        ON s.product_id = p.product_id
    LEFT JOIN goldusers_signup AS g
        ON s.user_id = g.user_id
)
SELECT
    order_type,
    SUM(price) AS total_revenue
FROM sales_with_flag
GROUP BY order_type;
GO


/* Q6. How long has each user been a gold member (in days) */
SELECT
    g.user_id,
    u.user_name,
    g.gold_signup_date,
    DATEDIFF(
        DAY,
        g.gold_signup_date,
        (SELECT MAX(created_date) FROM sales)  -- up to last transaction date
    ) AS days_as_gold_member
FROM goldusers_signup AS g
LEFT JOIN user_name AS u
    ON g.user_id = u.user_id
ORDER BY
    g.user_id;
GO


/* Q7. Most popular product among gold-member orders (after becoming gold) */
WITH gold_sales AS (
    SELECT
        s.product_id
    FROM goldusers_signup AS g
    JOIN sales AS s
        ON s.user_id = g.user_id
       AND s.created_date >= g.gold_signup_date
)
SELECT TOP (1)
    p.product_id,
    p.product_name,
    COUNT(*) AS times_ordered_by_gold
FROM gold_sales AS gs
JOIN product AS p
    ON gs.product_id = p.product_id
GROUP BY
    p.product_id,
    p.product_name
ORDER BY
    times_ordered_by_gold DESC;
GO


/* Q8. Total sales revenue generated in each year */
SELECT
    YEAR(s.created_date) AS sales_year,
    SUM(p.price)        AS total_revenue
FROM sales AS s
JOIN product AS p
    ON s.product_id = p.product_id
GROUP BY
    YEAR(s.created_date)
ORDER BY
    sales_year;
GO


/* Q9. Year-on-year change in sales revenue (amount & %) */
WITH yearly AS (
    SELECT
        YEAR(s.created_date) AS sales_year,
        SUM(p.price)        AS total_revenue
    FROM sales AS s
    JOIN product AS p
        ON s.product_id = p.product_id
    GROUP BY
        YEAR(s.created_date)
)
SELECT
    sales_year,
    total_revenue,
    LAG(total_revenue) OVER (ORDER BY sales_year) AS prev_year_revenue,
    CASE
        WHEN LAG(total_revenue) OVER (ORDER BY sales_year) IS NULL THEN NULL
        ELSE
            (total_revenue
             - LAG(total_revenue) OVER (ORDER BY sales_year))
             * 100.0
             / LAG(total_revenue) OVER (ORDER BY sales_year)
    END AS pct_change_vs_prev_year
FROM yearly
ORDER BY
    sales_year;
GO


/* Q10. Percentage of users who became gold members */
SELECT
    COUNT(DISTINCT g.user_id) * 100.0 / COUNT(DISTINCT u.user_id) AS pct_users_gold,
    COUNT(DISTINCT g.user_id)                                     AS total_gold_users,
    COUNT(DISTINCT u.user_id)                                     AS total_users
FROM users AS u
LEFT JOIN goldusers_signup AS g
    ON u.user_id = g.user_id;
GO


/* Q11. Orders by gold members: before vs after gold signup */
SELECT
    g.user_id,
    u.user_name,
    COUNT(s.product_id)                                                       AS total_orders,
    SUM(CASE WHEN s.created_date <  g.gold_signup_date THEN 1 ELSE 0 END)    AS orders_before_gold,
    SUM(CASE WHEN s.created_date >= g.gold_signup_date THEN 1 ELSE 0 END)    AS orders_after_gold
FROM goldusers_signup AS g
LEFT JOIN sales AS s
    ON s.user_id = g.user_id
LEFT JOIN user_name AS u
    ON u.user_id = g.user_id
GROUP BY
    g.user_id,
    u.user_name
ORDER BY
    g.user_id;
GO


/* Q12. Total amount each customer spent on online food delivery */
SELECT
    s.user_id,
    u.user_name,
    SUM(p.price) AS total_amount_spent
FROM sales AS s
JOIN product AS p
    ON s.product_id = p.product_id
LEFT JOIN user_name AS u
    ON u.user_id = s.user_id
GROUP BY
    s.user_id,
    u.user_name
ORDER BY
    total_amount_spent DESC;
GO


/* Q13. Frequency of customer visits (orders) on the platform */
SELECT
    s.user_id,
    u.user_name,
    COUNT(*)                         AS total_orders,
    COUNT(DISTINCT s.created_date)   AS distinct_visit_days
FROM sales AS s
LEFT JOIN user_name AS u
    ON u.user_id = s.user_id
GROUP BY
    s.user_id,
    u.user_name
ORDER BY
    total_orders DESC;
GO


/* Q14. First order purchased by each customer */
WITH ranked_orders AS (
    SELECT
        s.user_id,
        s.created_date,
        s.product_id,
        ROW_NUMBER() OVER (
            PARTITION BY s.user_id
            ORDER BY s.created_date, s.product_id
        ) AS rn
    FROM sales AS s
)
SELECT
    r.user_id,
    u.user_name,
    r.created_date      AS first_order_date,
    r.product_id,
    p.product_name
FROM ranked_orders AS r
JOIN product AS p
    ON r.product_id = p.product_id
LEFT JOIN user_name AS u
    ON u.user_id = r.user_id
WHERE r.rn = 1
ORDER BY
    r.user_id;
GO


/* Q15. Most purchased item on the menu and how many times */
SELECT TOP (1)
    p.product_id,
    p.product_name,
    COUNT(*) AS times_purchased
FROM sales AS s
JOIN product AS p
    ON s.product_id = p.product_id
GROUP BY
    p.product_id,
    p.product_name
ORDER BY
    times_purchased DESC;
GO


/* Q16. Most popular item for each customer */
WITH user_product_counts AS (
    SELECT
        s.user_id,
        s.product_id,
        COUNT(*) AS times_ordered
    FROM sales AS s
    GROUP BY
        s.user_id,
        s.product_id
),
ranked_items AS (
    SELECT
        up.*,
        ROW_NUMBER() OVER (
            PARTITION BY up.user_id
            ORDER BY up.times_ordered DESC, up.product_id
        ) AS rn
    FROM user_product_counts AS up
)
SELECT
    r.user_id,
    u.user_name,
    r.product_id,
    p.product_name,
    r.times_ordered
FROM ranked_items AS r
JOIN product AS p
    ON r.product_id = p.product_id
LEFT JOIN user_name AS u
    ON u.user_id = r.user_id
WHERE r.rn = 1
ORDER BY
    r.user_id;
GO


/* Q17. First item purchased AFTER becoming a gold member */
WITH gold_orders AS (
    SELECT
        g.user_id,
        g.gold_signup_date,
        s.created_date,
        s.product_id,
        ROW_NUMBER() OVER (
            PARTITION BY g.user_id
            ORDER BY s.created_date, s.product_id
        ) AS rn
    FROM goldusers_signup AS g
    JOIN sales AS s
        ON s.user_id = g.user_id
       AND s.created_date >= g.gold_signup_date
)
SELECT
    go.user_id,
    u.user_name,
    go.gold_signup_date,
    go.created_date       AS first_order_date_after_gold,
    go.product_id,
    p.product_name
FROM gold_orders AS go
JOIN product AS p
    ON go.product_id = p.product_id
LEFT JOIN user_name AS u
    ON u.user_id = go.user_id
WHERE go.rn = 1
ORDER BY
    go.user_id;
GO


/* Q18. Last item purchased BEFORE becoming a gold member */
WITH pre_gold_orders AS (
    SELECT
        g.user_id,
        g.gold_signup_date,
        s.created_date,
        s.product_id,
        ROW_NUMBER() OVER (
            PARTITION BY g.user_id
            ORDER BY s.created_date DESC, s.product_id DESC
        ) AS rn
    FROM goldusers_signup AS g
    JOIN sales AS s
        ON s.user_id = g.user_id
       AND s.created_date < g.gold_signup_date
)
SELECT
    pgo.user_id,
    u.user_name,
    pgo.gold_signup_date,
    pgo.created_date   AS last_order_date_before_gold,
    pgo.product_id,
    p.product_name
FROM pre_gold_orders AS pgo
JOIN product AS p
    ON pgo.product_id = p.product_id
LEFT JOIN user_name AS u
    ON u.user_id = pgo.user_id
WHERE pgo.rn = 1
ORDER BY
    pgo.user_id;
GO


/* Q19. Total orders & amount spent by each member BEFORE becoming gold */
SELECT
    g.user_id,
    u.user_name,
    COUNT(s.product_id)               AS orders_before_gold,
    SUM(p.price)                      AS amount_spent_before_gold
FROM goldusers_signup AS g
LEFT JOIN sales AS s
    ON s.user_id = g.user_id
   AND s.created_date < g.gold_signup_date
LEFT JOIN product AS p
    ON s.product_id = p.product_id
LEFT JOIN user_name AS u
    ON u.user_id = g.user_id
GROUP BY
    g.user_id,
    u.user_name
ORDER BY
    g.user_id;
GO


/* Q20. Rank all transactions for each member WHILE gold; others marked 'NA' */
WITH sales_with_gold_flag AS (
    SELECT
        s.user_id,
        s.created_date,
        s.product_id,
        CASE
            WHEN g.gold_signup_date IS NOT NULL
                 AND s.created_date >= g.gold_signup_date
                THEN 1
            ELSE 0
        END AS is_gold_txn
    FROM sales AS s
    LEFT JOIN goldusers_signup AS g
        ON s.user_id = g.user_id
),
ranked_gold_txns AS (
    SELECT
        swg.*,
        ROW_NUMBER() OVER (
            PARTITION BY swg.user_id
            ORDER BY swg.created_date, swg.product_id
        ) AS gold_rank
    FROM sales_with_gold_flag AS swg
    WHERE swg.is_gold_txn = 1
)
SELECT
    s.user_id,
    s.created_date,
    s.product_id,
    CASE
        WHEN s.is_gold_txn = 1
            THEN CAST(r.gold_rank AS VARCHAR(20))
        ELSE 'NA'
    END AS gold_txn_rank
FROM sales_with_gold_flag AS s
LEFT JOIN ranked_gold_txns AS r
    ON  r.user_id       = s.user_id
    AND r.created_date  = s.created_date
    AND r.product_id    = s.product_id
ORDER BY
    s.user_id,
    s.created_date,
    s.product_id;
GO